# Generated by Django 5.2.15 on 2026-07-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["invoice", "idempotency_key"], name="payment_invoice_idem"),
        ),
    ]
