# Generated by Django 5.2.15 on 2026-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_idempotency_key_payment_payment_invoice_idem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'purpose'), name='feestructure_tenant_purpose_unique'),
        ),
    ]
