# Generated by Django 5.2.15 on 2026-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='verification_token',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='verify_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
