# Generated by Django 5.2.15 on 2026-08-03 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.busschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='transport.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['schedule', 'ended_at'], name='trip_schedule_active'),
        ),
        migrations.AddIndex(
            model_name='breadcrumb',
            index=models.Index(fields=['trip', 'recorded_at'], name='breadcrumb_trip_time'),
        ),
        migrations.AddConstraint(
            model_name='breadcrumb',
            constraint=models.UniqueConstraint(fields=('trip', 'recorded_at'), name='unique_breadcrumb_per_instant'),
        ),
    ]
