# Generated by Django 5.2.15 on 2026-08-03 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_trip_breadcrumb_trip_trip_schedule_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_id', models.UUIDField()),
                ('student_user_code', models.CharField(max_length=30)),
                ('scanned_by', models.CharField(max_length=30)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('accepted', models.BooleanField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pass_id', 'scanned_at'], name='scanlog_pass_time')],
            },
        ),
    ]
