# Generated by Django 5.2.15 on 2026-07-03 05:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOutcome",
            fields=[
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invoice_id", models.UUIDField(db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")], max_length=20
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "invoice_id"),
                        name="payment_outcome_tenant_invoice_unique",
                    )
                ],
            },
        ),
    ]
