# Generated by Django 5.2.15 on 2026-07-04 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_paymentoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationImportBatch',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.UUIDField()),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationImportRow',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('room_id_raw', models.CharField(max_length=255)),
                ('student_email_raw', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='hostel.allocation')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='hostel.allocationimportbatch')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
