# Generated by Django 5.2.15 on 2026-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_allocationimportbatch_allocationimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationimportbatch',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allocationimportrow',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20),
        ),
    ]
