# Generated by Django 5.2.15 on 2026-07-06 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_import_skipped_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hostel.room')),
            ],
            options={
                'ordering': ['-requested_on'],
            },
        ),
    ]
