# Generated by Django 5.2.15 on 2026-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_roomrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant_id', 'student_id', 'room'), name='roomrequest_one_pending_per_student_room'),
        ),
    ]
