# Generated by Django 5.2.15 on 2026-08-02 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('push_token', models.CharField(blank=True, default='', max_length=255)),
                ('is_stale', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user'], name='device_tenant_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_device_per_user')],
            },
        ),
    ]
