# Generated by Django 5.2.15 on 2026-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("warden", "Warden"),
                    ("driver", "Driver"),
                    ("admin", "Admin"),
                    ("alumni", "Alumni"),
                    ("superadmin", "Super Admin"),
                    ("canteen_owner", "Canteen Owner"),
                ],
                max_length=20,
            ),
        ),
    ]
