# Generated by Django 5.2.15 on 2026-08-03 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMedia',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='grievance-media/')),
                ('sha256', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='grievance.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'purged_at'], name='media_purge_sweep')],
            },
        ),
    ]
