# Generated by Django 5.2.15 on 2026-07-03 12:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("roll_no", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=20)),
                ("semester", models.PositiveSmallIntegerField(default=1)),
                ("cgpa", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
