# Generated by Django 5.2.16 on 2026-07-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('tenant_id', 'user_code')},
        ),
    ]
