# Generated by Django 5.2.15 on 2026-07-02 20:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("tenant_id", models.UUIDField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at", "created_at"], name="suerp_commo_publish_e42b3f_idx"
                    )
                ],
            },
        ),
    ]
