# Generated by Django 5.2.15 on 2026-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway_ref",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
