# Generated by Django 5.2.15 on 2026-08-03 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('faculty_id', models.CharField(max_length=30)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_m', models.PositiveSmallIntegerField(default=50)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['course_code', 'opened_at'], name='session_course_time')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_user_code', models.CharField(max_length=30)),
                ('distance_m', models.FloatField()),
                ('mock_location', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='attendance.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'student_user_code'), name='one_mark_per_student_per_session')],
            },
        ),
    ]
